/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_MessageBoxFlags {
  public final static SDL_MessageBoxFlags SDL_MESSAGEBOX_ERROR = new SDL_MessageBoxFlags("SDL_MESSAGEBOX_ERROR", sdl2javaJNI.SDL_MESSAGEBOX_ERROR_get());
  public final static SDL_MessageBoxFlags SDL_MESSAGEBOX_WARNING = new SDL_MessageBoxFlags("SDL_MESSAGEBOX_WARNING", sdl2javaJNI.SDL_MESSAGEBOX_WARNING_get());
  public final static SDL_MessageBoxFlags SDL_MESSAGEBOX_INFORMATION = new SDL_MessageBoxFlags("SDL_MESSAGEBOX_INFORMATION", sdl2javaJNI.SDL_MESSAGEBOX_INFORMATION_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_MessageBoxFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_MessageBoxFlags.class + " with value " + swigValue);
  }

  private SDL_MessageBoxFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_MessageBoxFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_MessageBoxFlags(String swigName, SDL_MessageBoxFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_MessageBoxFlags[] swigValues = { SDL_MESSAGEBOX_ERROR, SDL_MESSAGEBOX_WARNING, SDL_MESSAGEBOX_INFORMATION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

