/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_MessageBoxColor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_MessageBoxColor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_MessageBoxColor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_MessageBoxColor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(short value) {
    sdl2javaJNI.SDL_MessageBoxColor_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return sdl2javaJNI.SDL_MessageBoxColor_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    sdl2javaJNI.SDL_MessageBoxColor_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return sdl2javaJNI.SDL_MessageBoxColor_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    sdl2javaJNI.SDL_MessageBoxColor_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return sdl2javaJNI.SDL_MessageBoxColor_b_get(swigCPtr, this);
  }

  public SDL_MessageBoxColor() {
    this(sdl2javaJNI.new_SDL_MessageBoxColor(), true);
  }

}
