/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_PowerState {
  public final static SDL_PowerState SDL_POWERSTATE_UNKNOWN = new SDL_PowerState("SDL_POWERSTATE_UNKNOWN");
  public final static SDL_PowerState SDL_POWERSTATE_ON_BATTERY = new SDL_PowerState("SDL_POWERSTATE_ON_BATTERY");
  public final static SDL_PowerState SDL_POWERSTATE_NO_BATTERY = new SDL_PowerState("SDL_POWERSTATE_NO_BATTERY");
  public final static SDL_PowerState SDL_POWERSTATE_CHARGING = new SDL_PowerState("SDL_POWERSTATE_CHARGING");
  public final static SDL_PowerState SDL_POWERSTATE_CHARGED = new SDL_PowerState("SDL_POWERSTATE_CHARGED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_PowerState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_PowerState.class + " with value " + swigValue);
  }

  private SDL_PowerState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_PowerState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_PowerState(String swigName, SDL_PowerState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_PowerState[] swigValues = { SDL_POWERSTATE_UNKNOWN, SDL_POWERSTATE_ON_BATTERY, SDL_POWERSTATE_NO_BATTERY, SDL_POWERSTATE_CHARGING, SDL_POWERSTATE_CHARGED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

