/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_MessageBoxButtonFlags {
  public final static SDL_MessageBoxButtonFlags SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT = new SDL_MessageBoxButtonFlags("SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT", sdl2javaJNI.SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT_get());
  public final static SDL_MessageBoxButtonFlags SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT = new SDL_MessageBoxButtonFlags("SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT", sdl2javaJNI.SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_MessageBoxButtonFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_MessageBoxButtonFlags.class + " with value " + swigValue);
  }

  private SDL_MessageBoxButtonFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_MessageBoxButtonFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_MessageBoxButtonFlags(String swigName, SDL_MessageBoxButtonFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_MessageBoxButtonFlags[] swigValues = { SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT, SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

