/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_assert_data {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_assert_data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_assert_data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_assert_data(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAlways_ignore(int value) {
    sdl2javaJNI.SDL_assert_data_always_ignore_set(swigCPtr, this, value);
  }

  public int getAlways_ignore() {
    return sdl2javaJNI.SDL_assert_data_always_ignore_get(swigCPtr, this);
  }

  public void setTrigger_count(long value) {
    sdl2javaJNI.SDL_assert_data_trigger_count_set(swigCPtr, this, value);
  }

  public long getTrigger_count() {
    return sdl2javaJNI.SDL_assert_data_trigger_count_get(swigCPtr, this);
  }

  public void setCondition(String value) {
    sdl2javaJNI.SDL_assert_data_condition_set(swigCPtr, this, value);
  }

  public String getCondition() {
    return sdl2javaJNI.SDL_assert_data_condition_get(swigCPtr, this);
  }

  public void setFilename(String value) {
    sdl2javaJNI.SDL_assert_data_filename_set(swigCPtr, this, value);
  }

  public String getFilename() {
    return sdl2javaJNI.SDL_assert_data_filename_get(swigCPtr, this);
  }

  public void setLinenum(int value) {
    sdl2javaJNI.SDL_assert_data_linenum_set(swigCPtr, this, value);
  }

  public int getLinenum() {
    return sdl2javaJNI.SDL_assert_data_linenum_get(swigCPtr, this);
  }

  public void setFunction(String value) {
    sdl2javaJNI.SDL_assert_data_function_set(swigCPtr, this, value);
  }

  public String getFunction() {
    return sdl2javaJNI.SDL_assert_data_function_get(swigCPtr, this);
  }

  public void setNext(SDL_assert_data value) {
    sdl2javaJNI.SDL_assert_data_next_set(swigCPtr, this, SDL_assert_data.getCPtr(value), value);
  }

  public SDL_assert_data getNext() {
    long cPtr = sdl2javaJNI.SDL_assert_data_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_assert_data(cPtr, false);
  }

  public SDL_assert_data() {
    this(sdl2javaJNI.new_SDL_assert_data(), true);
  }

}
