/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_JoyButtonEvent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_JoyButtonEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_JoyButtonEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_JoyButtonEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    sdl2javaJNI.SDL_JoyButtonEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return sdl2javaJNI.SDL_JoyButtonEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    sdl2javaJNI.SDL_JoyButtonEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return sdl2javaJNI.SDL_JoyButtonEvent_timestamp_get(swigCPtr, this);
  }

  public void setWhich(int value) {
    sdl2javaJNI.SDL_JoyButtonEvent_which_set(swigCPtr, this, value);
  }

  public int getWhich() {
    return sdl2javaJNI.SDL_JoyButtonEvent_which_get(swigCPtr, this);
  }

  public void setButton(short value) {
    sdl2javaJNI.SDL_JoyButtonEvent_button_set(swigCPtr, this, value);
  }

  public short getButton() {
    return sdl2javaJNI.SDL_JoyButtonEvent_button_get(swigCPtr, this);
  }

  public void setState(short value) {
    sdl2javaJNI.SDL_JoyButtonEvent_state_set(swigCPtr, this, value);
  }

  public short getState() {
    return sdl2javaJNI.SDL_JoyButtonEvent_state_get(swigCPtr, this);
  }

  public void setPadding1(short value) {
    sdl2javaJNI.SDL_JoyButtonEvent_padding1_set(swigCPtr, this, value);
  }

  public short getPadding1() {
    return sdl2javaJNI.SDL_JoyButtonEvent_padding1_get(swigCPtr, this);
  }

  public void setPadding2(short value) {
    sdl2javaJNI.SDL_JoyButtonEvent_padding2_set(swigCPtr, this, value);
  }

  public short getPadding2() {
    return sdl2javaJNI.SDL_JoyButtonEvent_padding2_get(swigCPtr, this);
  }

  public SDL_JoyButtonEvent() {
    this(sdl2javaJNI.new_SDL_JoyButtonEvent(), true);
  }

}
