/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_version {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_version(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_version obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_version(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMajor(short value) {
    sdl2javaJNI.SDL_version_major_set(swigCPtr, this, value);
  }

  public short getMajor() {
    return sdl2javaJNI.SDL_version_major_get(swigCPtr, this);
  }

  public void setMinor(short value) {
    sdl2javaJNI.SDL_version_minor_set(swigCPtr, this, value);
  }

  public short getMinor() {
    return sdl2javaJNI.SDL_version_minor_get(swigCPtr, this);
  }

  public void setPatch(short value) {
    sdl2javaJNI.SDL_version_patch_set(swigCPtr, this, value);
  }

  public short getPatch() {
    return sdl2javaJNI.SDL_version_patch_get(swigCPtr, this);
  }

  public SDL_version() {
    this(sdl2javaJNI.new_SDL_version(), true);
  }

}
