/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_errorcode {
  public final static SDL_errorcode SDL_ENOMEM = new SDL_errorcode("SDL_ENOMEM");
  public final static SDL_errorcode SDL_EFREAD = new SDL_errorcode("SDL_EFREAD");
  public final static SDL_errorcode SDL_EFWRITE = new SDL_errorcode("SDL_EFWRITE");
  public final static SDL_errorcode SDL_EFSEEK = new SDL_errorcode("SDL_EFSEEK");
  public final static SDL_errorcode SDL_UNSUPPORTED = new SDL_errorcode("SDL_UNSUPPORTED");
  public final static SDL_errorcode SDL_LASTERROR = new SDL_errorcode("SDL_LASTERROR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_errorcode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_errorcode.class + " with value " + swigValue);
  }

  private SDL_errorcode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_errorcode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_errorcode(String swigName, SDL_errorcode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_errorcode[] swigValues = { SDL_ENOMEM, SDL_EFREAD, SDL_EFWRITE, SDL_EFSEEK, SDL_UNSUPPORTED, SDL_LASTERROR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

