/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_MouseButtonEvent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_MouseButtonEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_MouseButtonEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_MouseButtonEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    sdl2javaJNI.SDL_MouseButtonEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return sdl2javaJNI.SDL_MouseButtonEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    sdl2javaJNI.SDL_MouseButtonEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return sdl2javaJNI.SDL_MouseButtonEvent_timestamp_get(swigCPtr, this);
  }

  public void setWindowID(long value) {
    sdl2javaJNI.SDL_MouseButtonEvent_windowID_set(swigCPtr, this, value);
  }

  public long getWindowID() {
    return sdl2javaJNI.SDL_MouseButtonEvent_windowID_get(swigCPtr, this);
  }

  public void setWhich(long value) {
    sdl2javaJNI.SDL_MouseButtonEvent_which_set(swigCPtr, this, value);
  }

  public long getWhich() {
    return sdl2javaJNI.SDL_MouseButtonEvent_which_get(swigCPtr, this);
  }

  public void setButton(short value) {
    sdl2javaJNI.SDL_MouseButtonEvent_button_set(swigCPtr, this, value);
  }

  public short getButton() {
    return sdl2javaJNI.SDL_MouseButtonEvent_button_get(swigCPtr, this);
  }

  public void setState(short value) {
    sdl2javaJNI.SDL_MouseButtonEvent_state_set(swigCPtr, this, value);
  }

  public short getState() {
    return sdl2javaJNI.SDL_MouseButtonEvent_state_get(swigCPtr, this);
  }

  public void setPadding1(short value) {
    sdl2javaJNI.SDL_MouseButtonEvent_padding1_set(swigCPtr, this, value);
  }

  public short getPadding1() {
    return sdl2javaJNI.SDL_MouseButtonEvent_padding1_get(swigCPtr, this);
  }

  public void setPadding2(short value) {
    sdl2javaJNI.SDL_MouseButtonEvent_padding2_set(swigCPtr, this, value);
  }

  public short getPadding2() {
    return sdl2javaJNI.SDL_MouseButtonEvent_padding2_get(swigCPtr, this);
  }

  public void setX(int value) {
    sdl2javaJNI.SDL_MouseButtonEvent_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return sdl2javaJNI.SDL_MouseButtonEvent_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    sdl2javaJNI.SDL_MouseButtonEvent_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return sdl2javaJNI.SDL_MouseButtonEvent_y_get(swigCPtr, this);
  }

  public SDL_MouseButtonEvent() {
    this(sdl2javaJNI.new_SDL_MouseButtonEvent(), true);
  }

}
