/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_Surface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_Surface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_Surface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_Surface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlags(long value) {
    sdl2javaJNI.SDL_Surface_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return sdl2javaJNI.SDL_Surface_flags_get(swigCPtr, this);
  }

  public void setFormat(SWIGTYPE_p_SDL_PixelFormat value) {
    sdl2javaJNI.SDL_Surface_format_set(swigCPtr, this, SWIGTYPE_p_SDL_PixelFormat.getCPtr(value));
  }

  public SWIGTYPE_p_SDL_PixelFormat getFormat() {
    long cPtr = sdl2javaJNI.SDL_Surface_format_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SDL_PixelFormat(cPtr, false);
  }

  public void setW(int value) {
    sdl2javaJNI.SDL_Surface_w_set(swigCPtr, this, value);
  }

  public int getW() {
    return sdl2javaJNI.SDL_Surface_w_get(swigCPtr, this);
  }

  public void setH(int value) {
    sdl2javaJNI.SDL_Surface_h_set(swigCPtr, this, value);
  }

  public int getH() {
    return sdl2javaJNI.SDL_Surface_h_get(swigCPtr, this);
  }

  public void setPitch(int value) {
    sdl2javaJNI.SDL_Surface_pitch_set(swigCPtr, this, value);
  }

  public int getPitch() {
    return sdl2javaJNI.SDL_Surface_pitch_get(swigCPtr, this);
  }

  public void setPixels(SWIGTYPE_p_void value) {
    sdl2javaJNI.SDL_Surface_pixels_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPixels() {
    long cPtr = sdl2javaJNI.SDL_Surface_pixels_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setUserdata(SWIGTYPE_p_void value) {
    sdl2javaJNI.SDL_Surface_userdata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserdata() {
    long cPtr = sdl2javaJNI.SDL_Surface_userdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setLocked(int value) {
    sdl2javaJNI.SDL_Surface_locked_set(swigCPtr, this, value);
  }

  public int getLocked() {
    return sdl2javaJNI.SDL_Surface_locked_get(swigCPtr, this);
  }

  public void setLock_data(SWIGTYPE_p_void value) {
    sdl2javaJNI.SDL_Surface_lock_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getLock_data() {
    long cPtr = sdl2javaJNI.SDL_Surface_lock_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setClip_rect(SDL_Rect value) {
    sdl2javaJNI.SDL_Surface_clip_rect_set(swigCPtr, this, SDL_Rect.getCPtr(value), value);
  }

  public SDL_Rect getClip_rect() {
    long cPtr = sdl2javaJNI.SDL_Surface_clip_rect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_Rect(cPtr, false);
  }

  public void setMap(SWIGTYPE_p_SDL_BlitMap value) {
    sdl2javaJNI.SDL_Surface_map_set(swigCPtr, this, SWIGTYPE_p_SDL_BlitMap.getCPtr(value));
  }

  public SWIGTYPE_p_SDL_BlitMap getMap() {
    long cPtr = sdl2javaJNI.SDL_Surface_map_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SDL_BlitMap(cPtr, false);
  }

  public void setRefcount(int value) {
    sdl2javaJNI.SDL_Surface_refcount_set(swigCPtr, this, value);
  }

  public int getRefcount() {
    return sdl2javaJNI.SDL_Surface_refcount_get(swigCPtr, this);
  }

  public SDL_Surface() {
    this(sdl2javaJNI.new_SDL_Surface(), true);
  }

}
