/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_HapticLeftRight {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_HapticLeftRight(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_HapticLeftRight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_HapticLeftRight(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    sdl2javaJNI.SDL_HapticLeftRight_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return sdl2javaJNI.SDL_HapticLeftRight_type_get(swigCPtr, this);
  }

  public void setLength(long value) {
    sdl2javaJNI.SDL_HapticLeftRight_length_set(swigCPtr, this, value);
  }

  public long getLength() {
    return sdl2javaJNI.SDL_HapticLeftRight_length_get(swigCPtr, this);
  }

  public void setLarge_magnitude(int value) {
    sdl2javaJNI.SDL_HapticLeftRight_large_magnitude_set(swigCPtr, this, value);
  }

  public int getLarge_magnitude() {
    return sdl2javaJNI.SDL_HapticLeftRight_large_magnitude_get(swigCPtr, this);
  }

  public void setSmall_magnitude(int value) {
    sdl2javaJNI.SDL_HapticLeftRight_small_magnitude_set(swigCPtr, this, value);
  }

  public int getSmall_magnitude() {
    return sdl2javaJNI.SDL_HapticLeftRight_small_magnitude_get(swigCPtr, this);
  }

  public SDL_HapticLeftRight() {
    this(sdl2javaJNI.new_SDL_HapticLeftRight(), true);
  }

}
