/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_Point {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_Point(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_Point obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_Point(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(int value) {
    sdl2javaJNI.SDL_Point_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return sdl2javaJNI.SDL_Point_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    sdl2javaJNI.SDL_Point_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return sdl2javaJNI.SDL_Point_y_get(swigCPtr, this);
  }

  public SDL_Point() {
    this(sdl2javaJNI.new_SDL_Point(), true);
  }

}
