/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_RWops_hidden_mem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_RWops_hidden_mem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_RWops_hidden_mem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_RWops_hidden_mem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBase(SWIGTYPE_p_unsigned_char value) {
    sdl2javaJNI.SDL_RWops_hidden_mem_base_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getBase() {
    long cPtr = sdl2javaJNI.SDL_RWops_hidden_mem_base_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setHere(SWIGTYPE_p_unsigned_char value) {
    sdl2javaJNI.SDL_RWops_hidden_mem_here_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getHere() {
    long cPtr = sdl2javaJNI.SDL_RWops_hidden_mem_here_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setStop(SWIGTYPE_p_unsigned_char value) {
    sdl2javaJNI.SDL_RWops_hidden_mem_stop_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getStop() {
    long cPtr = sdl2javaJNI.SDL_RWops_hidden_mem_stop_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SDL_RWops_hidden_mem() {
    this(sdl2javaJNI.new_SDL_RWops_hidden_mem(), true);
  }

}
