/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_JoyAxisEvent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_JoyAxisEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_JoyAxisEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_JoyAxisEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    sdl2javaJNI.SDL_JoyAxisEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return sdl2javaJNI.SDL_JoyAxisEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    sdl2javaJNI.SDL_JoyAxisEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return sdl2javaJNI.SDL_JoyAxisEvent_timestamp_get(swigCPtr, this);
  }

  public void setWhich(int value) {
    sdl2javaJNI.SDL_JoyAxisEvent_which_set(swigCPtr, this, value);
  }

  public int getWhich() {
    return sdl2javaJNI.SDL_JoyAxisEvent_which_get(swigCPtr, this);
  }

  public void setAxis(short value) {
    sdl2javaJNI.SDL_JoyAxisEvent_axis_set(swigCPtr, this, value);
  }

  public short getAxis() {
    return sdl2javaJNI.SDL_JoyAxisEvent_axis_get(swigCPtr, this);
  }

  public void setPadding1(short value) {
    sdl2javaJNI.SDL_JoyAxisEvent_padding1_set(swigCPtr, this, value);
  }

  public short getPadding1() {
    return sdl2javaJNI.SDL_JoyAxisEvent_padding1_get(swigCPtr, this);
  }

  public void setPadding2(short value) {
    sdl2javaJNI.SDL_JoyAxisEvent_padding2_set(swigCPtr, this, value);
  }

  public short getPadding2() {
    return sdl2javaJNI.SDL_JoyAxisEvent_padding2_get(swigCPtr, this);
  }

  public void setPadding3(short value) {
    sdl2javaJNI.SDL_JoyAxisEvent_padding3_set(swigCPtr, this, value);
  }

  public short getPadding3() {
    return sdl2javaJNI.SDL_JoyAxisEvent_padding3_get(swigCPtr, this);
  }

  public void setValue(short value) {
    sdl2javaJNI.SDL_JoyAxisEvent_value_set(swigCPtr, this, value);
  }

  public short getValue() {
    return sdl2javaJNI.SDL_JoyAxisEvent_value_get(swigCPtr, this);
  }

  public void setPadding4(int value) {
    sdl2javaJNI.SDL_JoyAxisEvent_padding4_set(swigCPtr, this, value);
  }

  public int getPadding4() {
    return sdl2javaJNI.SDL_JoyAxisEvent_padding4_get(swigCPtr, this);
  }

  public SDL_JoyAxisEvent() {
    this(sdl2javaJNI.new_SDL_JoyAxisEvent(), true);
  }

}
