/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_GameControllerButtonBind_value {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_GameControllerButtonBind_value(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_GameControllerButtonBind_value obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_GameControllerButtonBind_value(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setButton(int value) {
    sdl2javaJNI.SDL_GameControllerButtonBind_value_button_set(swigCPtr, this, value);
  }

  public int getButton() {
    return sdl2javaJNI.SDL_GameControllerButtonBind_value_button_get(swigCPtr, this);
  }

  public void setAxis(int value) {
    sdl2javaJNI.SDL_GameControllerButtonBind_value_axis_set(swigCPtr, this, value);
  }

  public int getAxis() {
    return sdl2javaJNI.SDL_GameControllerButtonBind_value_axis_get(swigCPtr, this);
  }

  public SDL_GameControllerButtonBind_value_hat getHat() {
    long cPtr = sdl2javaJNI.SDL_GameControllerButtonBind_value_hat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_GameControllerButtonBind_value_hat(cPtr, false);
  }

  public SDL_GameControllerButtonBind_value() {
    this(sdl2javaJNI.new_SDL_GameControllerButtonBind_value(), true);
  }

}
