/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_Event {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_Event(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_Event obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_Event(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    sdl2javaJNI.SDL_Event_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return sdl2javaJNI.SDL_Event_type_get(swigCPtr, this);
  }

  public void setCommon(SDL_CommonEvent value) {
    sdl2javaJNI.SDL_Event_common_set(swigCPtr, this, SDL_CommonEvent.getCPtr(value), value);
  }

  public SDL_CommonEvent getCommon() {
    long cPtr = sdl2javaJNI.SDL_Event_common_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_CommonEvent(cPtr, false);
  }

  public void setWindow(SDL_WindowEvent value) {
    sdl2javaJNI.SDL_Event_window_set(swigCPtr, this, SDL_WindowEvent.getCPtr(value), value);
  }

  public SDL_WindowEvent getWindow() {
    long cPtr = sdl2javaJNI.SDL_Event_window_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_WindowEvent(cPtr, false);
  }

  public void setKey(SDL_KeyboardEvent value) {
    sdl2javaJNI.SDL_Event_key_set(swigCPtr, this, SDL_KeyboardEvent.getCPtr(value), value);
  }

  public SDL_KeyboardEvent getKey() {
    long cPtr = sdl2javaJNI.SDL_Event_key_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_KeyboardEvent(cPtr, false);
  }

  public void setEdit(SDL_TextEditingEvent value) {
    sdl2javaJNI.SDL_Event_edit_set(swigCPtr, this, SDL_TextEditingEvent.getCPtr(value), value);
  }

  public SDL_TextEditingEvent getEdit() {
    long cPtr = sdl2javaJNI.SDL_Event_edit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_TextEditingEvent(cPtr, false);
  }

  public void setText(SDL_TextInputEvent value) {
    sdl2javaJNI.SDL_Event_text_set(swigCPtr, this, SDL_TextInputEvent.getCPtr(value), value);
  }

  public SDL_TextInputEvent getText() {
    long cPtr = sdl2javaJNI.SDL_Event_text_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_TextInputEvent(cPtr, false);
  }

  public void setMotion(SDL_MouseMotionEvent value) {
    sdl2javaJNI.SDL_Event_motion_set(swigCPtr, this, SDL_MouseMotionEvent.getCPtr(value), value);
  }

  public SDL_MouseMotionEvent getMotion() {
    long cPtr = sdl2javaJNI.SDL_Event_motion_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_MouseMotionEvent(cPtr, false);
  }

  public void setButton(SDL_MouseButtonEvent value) {
    sdl2javaJNI.SDL_Event_button_set(swigCPtr, this, SDL_MouseButtonEvent.getCPtr(value), value);
  }

  public SDL_MouseButtonEvent getButton() {
    long cPtr = sdl2javaJNI.SDL_Event_button_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_MouseButtonEvent(cPtr, false);
  }

  public void setWheel(SDL_MouseWheelEvent value) {
    sdl2javaJNI.SDL_Event_wheel_set(swigCPtr, this, SDL_MouseWheelEvent.getCPtr(value), value);
  }

  public SDL_MouseWheelEvent getWheel() {
    long cPtr = sdl2javaJNI.SDL_Event_wheel_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_MouseWheelEvent(cPtr, false);
  }

  public void setJaxis(SDL_JoyAxisEvent value) {
    sdl2javaJNI.SDL_Event_jaxis_set(swigCPtr, this, SDL_JoyAxisEvent.getCPtr(value), value);
  }

  public SDL_JoyAxisEvent getJaxis() {
    long cPtr = sdl2javaJNI.SDL_Event_jaxis_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_JoyAxisEvent(cPtr, false);
  }

  public void setJball(SDL_JoyBallEvent value) {
    sdl2javaJNI.SDL_Event_jball_set(swigCPtr, this, SDL_JoyBallEvent.getCPtr(value), value);
  }

  public SDL_JoyBallEvent getJball() {
    long cPtr = sdl2javaJNI.SDL_Event_jball_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_JoyBallEvent(cPtr, false);
  }

  public void setJhat(SDL_JoyHatEvent value) {
    sdl2javaJNI.SDL_Event_jhat_set(swigCPtr, this, SDL_JoyHatEvent.getCPtr(value), value);
  }

  public SDL_JoyHatEvent getJhat() {
    long cPtr = sdl2javaJNI.SDL_Event_jhat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_JoyHatEvent(cPtr, false);
  }

  public void setJbutton(SDL_JoyButtonEvent value) {
    sdl2javaJNI.SDL_Event_jbutton_set(swigCPtr, this, SDL_JoyButtonEvent.getCPtr(value), value);
  }

  public SDL_JoyButtonEvent getJbutton() {
    long cPtr = sdl2javaJNI.SDL_Event_jbutton_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_JoyButtonEvent(cPtr, false);
  }

  public void setJdevice(SDL_JoyDeviceEvent value) {
    sdl2javaJNI.SDL_Event_jdevice_set(swigCPtr, this, SDL_JoyDeviceEvent.getCPtr(value), value);
  }

  public SDL_JoyDeviceEvent getJdevice() {
    long cPtr = sdl2javaJNI.SDL_Event_jdevice_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_JoyDeviceEvent(cPtr, false);
  }

  public void setCaxis(SDL_ControllerAxisEvent value) {
    sdl2javaJNI.SDL_Event_caxis_set(swigCPtr, this, SDL_ControllerAxisEvent.getCPtr(value), value);
  }

  public SDL_ControllerAxisEvent getCaxis() {
    long cPtr = sdl2javaJNI.SDL_Event_caxis_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_ControllerAxisEvent(cPtr, false);
  }

  public void setCbutton(SDL_ControllerButtonEvent value) {
    sdl2javaJNI.SDL_Event_cbutton_set(swigCPtr, this, SDL_ControllerButtonEvent.getCPtr(value), value);
  }

  public SDL_ControllerButtonEvent getCbutton() {
    long cPtr = sdl2javaJNI.SDL_Event_cbutton_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_ControllerButtonEvent(cPtr, false);
  }

  public void setCdevice(SDL_ControllerDeviceEvent value) {
    sdl2javaJNI.SDL_Event_cdevice_set(swigCPtr, this, SDL_ControllerDeviceEvent.getCPtr(value), value);
  }

  public SDL_ControllerDeviceEvent getCdevice() {
    long cPtr = sdl2javaJNI.SDL_Event_cdevice_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_ControllerDeviceEvent(cPtr, false);
  }

  public void setQuit(SDL_QuitEvent value) {
    sdl2javaJNI.SDL_Event_quit_set(swigCPtr, this, SDL_QuitEvent.getCPtr(value), value);
  }

  public SDL_QuitEvent getQuit() {
    long cPtr = sdl2javaJNI.SDL_Event_quit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_QuitEvent(cPtr, false);
  }

  public void setUser(SDL_UserEvent value) {
    sdl2javaJNI.SDL_Event_user_set(swigCPtr, this, SDL_UserEvent.getCPtr(value), value);
  }

  public SDL_UserEvent getUser() {
    long cPtr = sdl2javaJNI.SDL_Event_user_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_UserEvent(cPtr, false);
  }

  public void setSyswm(SDL_SysWMEvent value) {
    sdl2javaJNI.SDL_Event_syswm_set(swigCPtr, this, SDL_SysWMEvent.getCPtr(value), value);
  }

  public SDL_SysWMEvent getSyswm() {
    long cPtr = sdl2javaJNI.SDL_Event_syswm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_SysWMEvent(cPtr, false);
  }

  public void setTfinger(SDL_TouchFingerEvent value) {
    sdl2javaJNI.SDL_Event_tfinger_set(swigCPtr, this, SDL_TouchFingerEvent.getCPtr(value), value);
  }

  public SDL_TouchFingerEvent getTfinger() {
    long cPtr = sdl2javaJNI.SDL_Event_tfinger_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_TouchFingerEvent(cPtr, false);
  }

  public void setMgesture(SDL_MultiGestureEvent value) {
    sdl2javaJNI.SDL_Event_mgesture_set(swigCPtr, this, SDL_MultiGestureEvent.getCPtr(value), value);
  }

  public SDL_MultiGestureEvent getMgesture() {
    long cPtr = sdl2javaJNI.SDL_Event_mgesture_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_MultiGestureEvent(cPtr, false);
  }

  public void setDgesture(SDL_DollarGestureEvent value) {
    sdl2javaJNI.SDL_Event_dgesture_set(swigCPtr, this, SDL_DollarGestureEvent.getCPtr(value), value);
  }

  public SDL_DollarGestureEvent getDgesture() {
    long cPtr = sdl2javaJNI.SDL_Event_dgesture_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_DollarGestureEvent(cPtr, false);
  }

  public void setDrop(SDL_DropEvent value) {
    sdl2javaJNI.SDL_Event_drop_set(swigCPtr, this, SDL_DropEvent.getCPtr(value), value);
  }

  public SDL_DropEvent getDrop() {
    long cPtr = sdl2javaJNI.SDL_Event_drop_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_DropEvent(cPtr, false);
  }

  public void setPadding(SWIGTYPE_p_unsigned_char value) {
    sdl2javaJNI.SDL_Event_padding_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getPadding() {
    long cPtr = sdl2javaJNI.SDL_Event_padding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SDL_Event() {
    this(sdl2javaJNI.new_SDL_Event(), true);
  }

}
