/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_HapticCondition {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_HapticCondition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_HapticCondition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_HapticCondition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    sdl2javaJNI.SDL_HapticCondition_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return sdl2javaJNI.SDL_HapticCondition_type_get(swigCPtr, this);
  }

  public void setDirection(SDL_HapticDirection value) {
    sdl2javaJNI.SDL_HapticCondition_direction_set(swigCPtr, this, SDL_HapticDirection.getCPtr(value), value);
  }

  public SDL_HapticDirection getDirection() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_direction_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_HapticDirection(cPtr, false);
  }

  public void setLength(long value) {
    sdl2javaJNI.SDL_HapticCondition_length_set(swigCPtr, this, value);
  }

  public long getLength() {
    return sdl2javaJNI.SDL_HapticCondition_length_get(swigCPtr, this);
  }

  public void setDelay(int value) {
    sdl2javaJNI.SDL_HapticCondition_delay_set(swigCPtr, this, value);
  }

  public int getDelay() {
    return sdl2javaJNI.SDL_HapticCondition_delay_get(swigCPtr, this);
  }

  public void setButton(int value) {
    sdl2javaJNI.SDL_HapticCondition_button_set(swigCPtr, this, value);
  }

  public int getButton() {
    return sdl2javaJNI.SDL_HapticCondition_button_get(swigCPtr, this);
  }

  public void setInterval(int value) {
    sdl2javaJNI.SDL_HapticCondition_interval_set(swigCPtr, this, value);
  }

  public int getInterval() {
    return sdl2javaJNI.SDL_HapticCondition_interval_get(swigCPtr, this);
  }

  public void setRight_sat(SWIGTYPE_p_unsigned_short value) {
    sdl2javaJNI.SDL_HapticCondition_right_sat_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getRight_sat() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_right_sat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setLeft_sat(SWIGTYPE_p_unsigned_short value) {
    sdl2javaJNI.SDL_HapticCondition_left_sat_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getLeft_sat() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_left_sat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setRight_coeff(SWIGTYPE_p_short value) {
    sdl2javaJNI.SDL_HapticCondition_right_coeff_set(swigCPtr, this, SWIGTYPE_p_short.getCPtr(value));
  }

  public SWIGTYPE_p_short getRight_coeff() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_right_coeff_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_short(cPtr, false);
  }

  public void setLeft_coeff(SWIGTYPE_p_short value) {
    sdl2javaJNI.SDL_HapticCondition_left_coeff_set(swigCPtr, this, SWIGTYPE_p_short.getCPtr(value));
  }

  public SWIGTYPE_p_short getLeft_coeff() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_left_coeff_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_short(cPtr, false);
  }

  public void setDeadband(SWIGTYPE_p_unsigned_short value) {
    sdl2javaJNI.SDL_HapticCondition_deadband_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getDeadband() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_deadband_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setCenter(SWIGTYPE_p_short value) {
    sdl2javaJNI.SDL_HapticCondition_center_set(swigCPtr, this, SWIGTYPE_p_short.getCPtr(value));
  }

  public SWIGTYPE_p_short getCenter() {
    long cPtr = sdl2javaJNI.SDL_HapticCondition_center_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_short(cPtr, false);
  }

  public SDL_HapticCondition() {
    this(sdl2javaJNI.new_SDL_HapticCondition(), true);
  }

}
