/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_JoyBallEvent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_JoyBallEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_JoyBallEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_JoyBallEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    sdl2javaJNI.SDL_JoyBallEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return sdl2javaJNI.SDL_JoyBallEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    sdl2javaJNI.SDL_JoyBallEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return sdl2javaJNI.SDL_JoyBallEvent_timestamp_get(swigCPtr, this);
  }

  public void setWhich(int value) {
    sdl2javaJNI.SDL_JoyBallEvent_which_set(swigCPtr, this, value);
  }

  public int getWhich() {
    return sdl2javaJNI.SDL_JoyBallEvent_which_get(swigCPtr, this);
  }

  public void setBall(short value) {
    sdl2javaJNI.SDL_JoyBallEvent_ball_set(swigCPtr, this, value);
  }

  public short getBall() {
    return sdl2javaJNI.SDL_JoyBallEvent_ball_get(swigCPtr, this);
  }

  public void setPadding1(short value) {
    sdl2javaJNI.SDL_JoyBallEvent_padding1_set(swigCPtr, this, value);
  }

  public short getPadding1() {
    return sdl2javaJNI.SDL_JoyBallEvent_padding1_get(swigCPtr, this);
  }

  public void setPadding2(short value) {
    sdl2javaJNI.SDL_JoyBallEvent_padding2_set(swigCPtr, this, value);
  }

  public short getPadding2() {
    return sdl2javaJNI.SDL_JoyBallEvent_padding2_get(swigCPtr, this);
  }

  public void setPadding3(short value) {
    sdl2javaJNI.SDL_JoyBallEvent_padding3_set(swigCPtr, this, value);
  }

  public short getPadding3() {
    return sdl2javaJNI.SDL_JoyBallEvent_padding3_get(swigCPtr, this);
  }

  public void setXrel(short value) {
    sdl2javaJNI.SDL_JoyBallEvent_xrel_set(swigCPtr, this, value);
  }

  public short getXrel() {
    return sdl2javaJNI.SDL_JoyBallEvent_xrel_get(swigCPtr, this);
  }

  public void setYrel(short value) {
    sdl2javaJNI.SDL_JoyBallEvent_yrel_set(swigCPtr, this, value);
  }

  public short getYrel() {
    return sdl2javaJNI.SDL_JoyBallEvent_yrel_get(swigCPtr, this);
  }

  public SDL_JoyBallEvent() {
    this(sdl2javaJNI.new_SDL_JoyBallEvent(), true);
  }

}
