/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_atomic_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_atomic_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_atomic_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_atomic_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(int value) {
    sdl2javaJNI.SDL_atomic_t_value_set(swigCPtr, this, value);
  }

  public int getValue() {
    return sdl2javaJNI.SDL_atomic_t_value_get(swigCPtr, this);
  }

  public SDL_atomic_t() {
    this(sdl2javaJNI.new_SDL_atomic_t(), true);
  }

}
