/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_RendererInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_RendererInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_RendererInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_RendererInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    sdl2javaJNI.SDL_RendererInfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return sdl2javaJNI.SDL_RendererInfo_name_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    sdl2javaJNI.SDL_RendererInfo_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return sdl2javaJNI.SDL_RendererInfo_flags_get(swigCPtr, this);
  }

  public void setNum_texture_formats(long value) {
    sdl2javaJNI.SDL_RendererInfo_num_texture_formats_set(swigCPtr, this, value);
  }

  public long getNum_texture_formats() {
    return sdl2javaJNI.SDL_RendererInfo_num_texture_formats_get(swigCPtr, this);
  }

  public void setTexture_formats(SWIGTYPE_p_unsigned_int value) {
    sdl2javaJNI.SDL_RendererInfo_texture_formats_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getTexture_formats() {
    long cPtr = sdl2javaJNI.SDL_RendererInfo_texture_formats_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setMax_texture_width(int value) {
    sdl2javaJNI.SDL_RendererInfo_max_texture_width_set(swigCPtr, this, value);
  }

  public int getMax_texture_width() {
    return sdl2javaJNI.SDL_RendererInfo_max_texture_width_get(swigCPtr, this);
  }

  public void setMax_texture_height(int value) {
    sdl2javaJNI.SDL_RendererInfo_max_texture_height_set(swigCPtr, this, value);
  }

  public int getMax_texture_height() {
    return sdl2javaJNI.SDL_RendererInfo_max_texture_height_get(swigCPtr, this);
  }

  public SDL_RendererInfo() {
    this(sdl2javaJNI.new_SDL_RendererInfo(), true);
  }

}
