/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_GameControllerButtonBind_value_hat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_GameControllerButtonBind_value_hat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_GameControllerButtonBind_value_hat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_GameControllerButtonBind_value_hat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHat(int value) {
    sdl2javaJNI.SDL_GameControllerButtonBind_value_hat_hat_set(swigCPtr, this, value);
  }

  public int getHat() {
    return sdl2javaJNI.SDL_GameControllerButtonBind_value_hat_hat_get(swigCPtr, this);
  }

  public void setHat_mask(int value) {
    sdl2javaJNI.SDL_GameControllerButtonBind_value_hat_hat_mask_set(swigCPtr, this, value);
  }

  public int getHat_mask() {
    return sdl2javaJNI.SDL_GameControllerButtonBind_value_hat_hat_mask_get(swigCPtr, this);
  }

  public SDL_GameControllerButtonBind_value_hat() {
    this(sdl2javaJNI.new_SDL_GameControllerButtonBind_value_hat(), true);
  }

}
