/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_RWops_hidden_unknown {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_RWops_hidden_unknown(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_RWops_hidden_unknown obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_RWops_hidden_unknown(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData1(SWIGTYPE_p_void value) {
    sdl2javaJNI.SDL_RWops_hidden_unknown_data1_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData1() {
    long cPtr = sdl2javaJNI.SDL_RWops_hidden_unknown_data1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setData2(SWIGTYPE_p_void value) {
    sdl2javaJNI.SDL_RWops_hidden_unknown_data2_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData2() {
    long cPtr = sdl2javaJNI.SDL_RWops_hidden_unknown_data2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SDL_RWops_hidden_unknown() {
    this(sdl2javaJNI.new_SDL_RWops_hidden_unknown(), true);
  }

}
