/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_Keysym {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_Keysym(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_Keysym obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_Keysym(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setScancode(SDL_Scancode value) {
    sdl2javaJNI.SDL_Keysym_scancode_set(swigCPtr, this, value.swigValue());
  }

  public SDL_Scancode getScancode() {
    return SDL_Scancode.swigToEnum(sdl2javaJNI.SDL_Keysym_scancode_get(swigCPtr, this));
  }

  public void setSym(int value) {
    sdl2javaJNI.SDL_Keysym_sym_set(swigCPtr, this, value);
  }

  public int getSym() {
    return sdl2javaJNI.SDL_Keysym_sym_get(swigCPtr, this);
  }

  public void setMod(int value) {
    sdl2javaJNI.SDL_Keysym_mod_set(swigCPtr, this, value);
  }

  public int getMod() {
    return sdl2javaJNI.SDL_Keysym_mod_get(swigCPtr, this);
  }

  public void setUnused(long value) {
    sdl2javaJNI.SDL_Keysym_unused_set(swigCPtr, this, value);
  }

  public long getUnused() {
    return sdl2javaJNI.SDL_Keysym_unused_get(swigCPtr, this);
  }

  public SDL_Keysym() {
    this(sdl2javaJNI.new_SDL_Keysym(), true);
  }

}
