/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_GameControllerButton {
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_INVALID = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_INVALID", sdl2javaJNI.SDL_CONTROLLER_BUTTON_INVALID_get());
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_A = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_A");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_B = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_B");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_X = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_X");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_Y = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_Y");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_BACK = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_BACK");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_GUIDE = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_GUIDE");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_START = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_START");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_LEFTSTICK = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_LEFTSTICK");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_RIGHTSTICK = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_RIGHTSTICK");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_LEFTSHOULDER = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_LEFTSHOULDER");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_RIGHTSHOULDER = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_RIGHTSHOULDER");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_DPAD_UP = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_DPAD_UP");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_DPAD_DOWN = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_DPAD_DOWN");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_DPAD_LEFT = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_DPAD_LEFT");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_DPAD_RIGHT = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_DPAD_RIGHT");
  public final static SDL_GameControllerButton SDL_CONTROLLER_BUTTON_MAX = new SDL_GameControllerButton("SDL_CONTROLLER_BUTTON_MAX");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_GameControllerButton swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_GameControllerButton.class + " with value " + swigValue);
  }

  private SDL_GameControllerButton(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_GameControllerButton(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_GameControllerButton(String swigName, SDL_GameControllerButton swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_GameControllerButton[] swigValues = { SDL_CONTROLLER_BUTTON_INVALID, SDL_CONTROLLER_BUTTON_A, SDL_CONTROLLER_BUTTON_B, SDL_CONTROLLER_BUTTON_X, SDL_CONTROLLER_BUTTON_Y, SDL_CONTROLLER_BUTTON_BACK, SDL_CONTROLLER_BUTTON_GUIDE, SDL_CONTROLLER_BUTTON_START, SDL_CONTROLLER_BUTTON_LEFTSTICK, SDL_CONTROLLER_BUTTON_RIGHTSTICK, SDL_CONTROLLER_BUTTON_LEFTSHOULDER, SDL_CONTROLLER_BUTTON_RIGHTSHOULDER, SDL_CONTROLLER_BUTTON_DPAD_UP, SDL_CONTROLLER_BUTTON_DPAD_DOWN, SDL_CONTROLLER_BUTTON_DPAD_LEFT, SDL_CONTROLLER_BUTTON_DPAD_RIGHT, SDL_CONTROLLER_BUTTON_MAX };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

