/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_TouchFingerEvent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_TouchFingerEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_TouchFingerEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_TouchFingerEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    sdl2javaJNI.SDL_TouchFingerEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return sdl2javaJNI.SDL_TouchFingerEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    sdl2javaJNI.SDL_TouchFingerEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return sdl2javaJNI.SDL_TouchFingerEvent_timestamp_get(swigCPtr, this);
  }

  public void setTouchId(SWIGTYPE_p_SDL_TouchID value) {
    sdl2javaJNI.SDL_TouchFingerEvent_touchId_set(swigCPtr, this, SWIGTYPE_p_SDL_TouchID.getCPtr(value));
  }

  public SWIGTYPE_p_SDL_TouchID getTouchId() {
    return new SWIGTYPE_p_SDL_TouchID(sdl2javaJNI.SDL_TouchFingerEvent_touchId_get(swigCPtr, this), true);
  }

  public void setFingerId(SWIGTYPE_p_SDL_FingerID value) {
    sdl2javaJNI.SDL_TouchFingerEvent_fingerId_set(swigCPtr, this, SWIGTYPE_p_SDL_FingerID.getCPtr(value));
  }

  public SWIGTYPE_p_SDL_FingerID getFingerId() {
    return new SWIGTYPE_p_SDL_FingerID(sdl2javaJNI.SDL_TouchFingerEvent_fingerId_get(swigCPtr, this), true);
  }

  public void setX(float value) {
    sdl2javaJNI.SDL_TouchFingerEvent_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return sdl2javaJNI.SDL_TouchFingerEvent_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    sdl2javaJNI.SDL_TouchFingerEvent_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return sdl2javaJNI.SDL_TouchFingerEvent_y_get(swigCPtr, this);
  }

  public void setDx(float value) {
    sdl2javaJNI.SDL_TouchFingerEvent_dx_set(swigCPtr, this, value);
  }

  public float getDx() {
    return sdl2javaJNI.SDL_TouchFingerEvent_dx_get(swigCPtr, this);
  }

  public void setDy(float value) {
    sdl2javaJNI.SDL_TouchFingerEvent_dy_set(swigCPtr, this, value);
  }

  public float getDy() {
    return sdl2javaJNI.SDL_TouchFingerEvent_dy_get(swigCPtr, this);
  }

  public void setPressure(float value) {
    sdl2javaJNI.SDL_TouchFingerEvent_pressure_set(swigCPtr, this, value);
  }

  public float getPressure() {
    return sdl2javaJNI.SDL_TouchFingerEvent_pressure_get(swigCPtr, this);
  }

  public SDL_TouchFingerEvent() {
    this(sdl2javaJNI.new_SDL_TouchFingerEvent(), true);
  }

}
