/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_MessageBoxButtonData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_MessageBoxButtonData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_MessageBoxButtonData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_MessageBoxButtonData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlags(long value) {
    sdl2javaJNI.SDL_MessageBoxButtonData_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return sdl2javaJNI.SDL_MessageBoxButtonData_flags_get(swigCPtr, this);
  }

  public void setButtonid(int value) {
    sdl2javaJNI.SDL_MessageBoxButtonData_buttonid_set(swigCPtr, this, value);
  }

  public int getButtonid() {
    return sdl2javaJNI.SDL_MessageBoxButtonData_buttonid_get(swigCPtr, this);
  }

  public void setText(String value) {
    sdl2javaJNI.SDL_MessageBoxButtonData_text_set(swigCPtr, this, value);
  }

  public String getText() {
    return sdl2javaJNI.SDL_MessageBoxButtonData_text_get(swigCPtr, this);
  }

  public SDL_MessageBoxButtonData() {
    this(sdl2javaJNI.new_SDL_MessageBoxButtonData(), true);
  }

}
