/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_GameControllerBindType {
  public final static SDL_GameControllerBindType SDL_CONTROLLER_BINDTYPE_NONE = new SDL_GameControllerBindType("SDL_CONTROLLER_BINDTYPE_NONE", sdl2javaJNI.SDL_CONTROLLER_BINDTYPE_NONE_get());
  public final static SDL_GameControllerBindType SDL_CONTROLLER_BINDTYPE_BUTTON = new SDL_GameControllerBindType("SDL_CONTROLLER_BINDTYPE_BUTTON");
  public final static SDL_GameControllerBindType SDL_CONTROLLER_BINDTYPE_AXIS = new SDL_GameControllerBindType("SDL_CONTROLLER_BINDTYPE_AXIS");
  public final static SDL_GameControllerBindType SDL_CONTROLLER_BINDTYPE_HAT = new SDL_GameControllerBindType("SDL_CONTROLLER_BINDTYPE_HAT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_GameControllerBindType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_GameControllerBindType.class + " with value " + swigValue);
  }

  private SDL_GameControllerBindType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_GameControllerBindType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_GameControllerBindType(String swigName, SDL_GameControllerBindType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_GameControllerBindType[] swigValues = { SDL_CONTROLLER_BINDTYPE_NONE, SDL_CONTROLLER_BINDTYPE_BUTTON, SDL_CONTROLLER_BINDTYPE_AXIS, SDL_CONTROLLER_BINDTYPE_HAT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

