/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_KeyboardEvent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_KeyboardEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_KeyboardEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_KeyboardEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    sdl2javaJNI.SDL_KeyboardEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return sdl2javaJNI.SDL_KeyboardEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    sdl2javaJNI.SDL_KeyboardEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return sdl2javaJNI.SDL_KeyboardEvent_timestamp_get(swigCPtr, this);
  }

  public void setWindowID(long value) {
    sdl2javaJNI.SDL_KeyboardEvent_windowID_set(swigCPtr, this, value);
  }

  public long getWindowID() {
    return sdl2javaJNI.SDL_KeyboardEvent_windowID_get(swigCPtr, this);
  }

  public void setState(short value) {
    sdl2javaJNI.SDL_KeyboardEvent_state_set(swigCPtr, this, value);
  }

  public short getState() {
    return sdl2javaJNI.SDL_KeyboardEvent_state_get(swigCPtr, this);
  }

  public void setRepeat(short value) {
    sdl2javaJNI.SDL_KeyboardEvent_repeat_set(swigCPtr, this, value);
  }

  public short getRepeat() {
    return sdl2javaJNI.SDL_KeyboardEvent_repeat_get(swigCPtr, this);
  }

  public void setPadding2(short value) {
    sdl2javaJNI.SDL_KeyboardEvent_padding2_set(swigCPtr, this, value);
  }

  public short getPadding2() {
    return sdl2javaJNI.SDL_KeyboardEvent_padding2_get(swigCPtr, this);
  }

  public void setPadding3(short value) {
    sdl2javaJNI.SDL_KeyboardEvent_padding3_set(swigCPtr, this, value);
  }

  public short getPadding3() {
    return sdl2javaJNI.SDL_KeyboardEvent_padding3_get(swigCPtr, this);
  }

  public void setKeysym(SDL_Keysym value) {
    sdl2javaJNI.SDL_KeyboardEvent_keysym_set(swigCPtr, this, SDL_Keysym.getCPtr(value), value);
  }

  public SDL_Keysym getKeysym() {
    long cPtr = sdl2javaJNI.SDL_KeyboardEvent_keysym_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDL_Keysym(cPtr, false);
  }

  public SDL_KeyboardEvent() {
    this(sdl2javaJNI.new_SDL_KeyboardEvent(), true);
  }

}
