/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_HapticDirection {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_HapticDirection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_HapticDirection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_HapticDirection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(short value) {
    sdl2javaJNI.SDL_HapticDirection_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return sdl2javaJNI.SDL_HapticDirection_type_get(swigCPtr, this);
  }

  public void setDir(SWIGTYPE_p_int value) {
    sdl2javaJNI.SDL_HapticDirection_dir_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getDir() {
    long cPtr = sdl2javaJNI.SDL_HapticDirection_dir_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public SDL_HapticDirection() {
    this(sdl2javaJNI.new_SDL_HapticDirection(), true);
  }

}
