/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public final class SDL_LogPriority {
  public final static SDL_LogPriority SDL_LOG_PRIORITY_VERBOSE = new SDL_LogPriority("SDL_LOG_PRIORITY_VERBOSE", sdl2javaJNI.SDL_LOG_PRIORITY_VERBOSE_get());
  public final static SDL_LogPriority SDL_LOG_PRIORITY_DEBUG = new SDL_LogPriority("SDL_LOG_PRIORITY_DEBUG");
  public final static SDL_LogPriority SDL_LOG_PRIORITY_INFO = new SDL_LogPriority("SDL_LOG_PRIORITY_INFO");
  public final static SDL_LogPriority SDL_LOG_PRIORITY_WARN = new SDL_LogPriority("SDL_LOG_PRIORITY_WARN");
  public final static SDL_LogPriority SDL_LOG_PRIORITY_ERROR = new SDL_LogPriority("SDL_LOG_PRIORITY_ERROR");
  public final static SDL_LogPriority SDL_LOG_PRIORITY_CRITICAL = new SDL_LogPriority("SDL_LOG_PRIORITY_CRITICAL");
  public final static SDL_LogPriority SDL_NUM_LOG_PRIORITIES = new SDL_LogPriority("SDL_NUM_LOG_PRIORITIES");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_LogPriority swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_LogPriority.class + " with value " + swigValue);
  }

  private SDL_LogPriority(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_LogPriority(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_LogPriority(String swigName, SDL_LogPriority swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_LogPriority[] swigValues = { SDL_LOG_PRIORITY_VERBOSE, SDL_LOG_PRIORITY_DEBUG, SDL_LOG_PRIORITY_INFO, SDL_LOG_PRIORITY_WARN, SDL_LOG_PRIORITY_ERROR, SDL_LOG_PRIORITY_CRITICAL, SDL_NUM_LOG_PRIORITIES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

