/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SDL_SysWMEvent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_SysWMEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_SysWMEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sdl2javaJNI.delete_SDL_SysWMEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    sdl2javaJNI.SDL_SysWMEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return sdl2javaJNI.SDL_SysWMEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    sdl2javaJNI.SDL_SysWMEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return sdl2javaJNI.SDL_SysWMEvent_timestamp_get(swigCPtr, this);
  }

  public void setMsg(SWIGTYPE_p_SDL_SysWMmsg value) {
    sdl2javaJNI.SDL_SysWMEvent_msg_set(swigCPtr, this, SWIGTYPE_p_SDL_SysWMmsg.getCPtr(value));
  }

  public SWIGTYPE_p_SDL_SysWMmsg getMsg() {
    long cPtr = sdl2javaJNI.SDL_SysWMEvent_msg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SDL_SysWMmsg(cPtr, false);
  }

  public SDL_SysWMEvent() {
    this(sdl2javaJNI.new_SDL_SysWMEvent(), true);
  }

}
