/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SWIGTYPE_p_f_unsigned_int_p_void__unsigned_int {
  private long swigCPtr;

  protected SWIGTYPE_p_f_unsigned_int_p_void__unsigned_int(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_unsigned_int_p_void__unsigned_int() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_unsigned_int_p_void__unsigned_int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

