/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libsdl2;

public class SWIGTYPE_p_f_p_struct_SDL_RWops_p_q_const__void_size_t_size_t__size_t {
  private long swigCPtr;

  protected SWIGTYPE_p_f_p_struct_SDL_RWops_p_q_const__void_size_t_size_t__size_t(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_struct_SDL_RWops_p_q_const__void_size_t_size_t__size_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_struct_SDL_RWops_p_q_const__void_size_t_size_t__size_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

